import {defineArrayMember, defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site settings',
  type: 'document',
  groups: [
    {name: 'nav', title: 'Navigation', default: true},
    {name: 'footer', title: 'Footer'},
    {name: 'brand', title: 'Brand'},
  ],
  fields: [
    defineField({
      name: 'brandName',
      title: 'Brand name',
      type: 'string',
      group: 'brand',
      initialValue: 'Compound Growth Studio',
    }),
    defineField({
      name: 'brandMark',
      title: 'Brand mark',
      type: 'string',
      group: 'brand',
      initialValue: 'CG',
      description: 'Short mark shown in the logo square',
    }),
    defineField({
      name: 'navItems',
      title: 'Nav links',
      type: 'array',
      group: 'nav',
      of: [defineArrayMember({type: 'link'})],
    }),
    defineField({
      name: 'navCtaLabel',
      title: 'Nav CTA label',
      type: 'string',
      group: 'nav',
      initialValue: 'Find Your Growth Gaps',
    }),
    defineField({
      name: 'navCtaHref',
      title: 'Nav CTA href',
      type: 'string',
      group: 'nav',
      initialValue: '/contact/',
    }),
    defineField({
      name: 'primaryCtaLabel',
      title: 'Primary CTA label (sitewide default)',
      type: 'string',
      group: 'nav',
      initialValue: 'Find the Gaps in Your Growth System',
    }),
    defineField({
      name: 'footerBlurb',
      title: 'Footer blurb',
      type: 'text',
      rows: 4,
      group: 'footer',
    }),
    defineField({
      name: 'footerLeadMagnetTitle',
      title: 'Footer lead magnet title',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerLeadMagnet',
      title: 'Footer lead magnet form',
      type: 'formCopy',
      group: 'footer',
    }),
    defineField({
      name: 'footerExploreHeading',
      title: 'Explore column heading',
      type: 'string',
      group: 'footer',
      initialValue: 'Explore',
    }),
    defineField({
      name: 'footerExploreLinks',
      title: 'Explore links',
      type: 'array',
      group: 'footer',
      of: [defineArrayMember({type: 'link'})],
    }),
    defineField({
      name: 'footerGetStartedHeading',
      title: 'Get started column heading',
      type: 'string',
      group: 'footer',
      initialValue: 'Get started',
    }),
    defineField({
      name: 'footerGetStartedLinks',
      title: 'Get started links',
      type: 'array',
      group: 'footer',
      of: [defineArrayMember({type: 'link'})],
    }),
    defineField({
      name: 'footerDisclaimer',
      title: 'Medical disclaimer',
      type: 'text',
      rows: 4,
      group: 'footer',
    }),
  ],
  preview: {prepare: () => ({title: 'Site settings'})},
})
